% u-shape3D Configuration for 48hcontrol
% Generated by vessel segmentation pipeline

p.meshMode = 'loadMask';
p.maskDir = '/Users/philippkaintoch/Documents/Projects/09_Milos_Revision/output/48hcontrol_slices';
p.maskName = 'slice_';
p.smoothImageSize = 1.0;  % Pre-smoothed masks
p.scaleOtsu = 0.35;       % Optimized for vessel masks
p.smoothMeshIterations = 10;
p.curvatureMedianFilterRadius = 2;
p.removeSmallComponents = 1;

% Processing parameters used:
% Gamma correction: 1.8
% Smoothing sigma: 1.5
% Distance weight: 0.4
